#+TITLE: There There Diagnostic Essay
#+AUTHOR: Houjun Liu
#+SOURCE: KBMasterIndexEng301
#+COURSE: ENG301

* General Information
  | Due Date | Topic                            | Important Documents         |
  |----------+----------------------------------+-----------------------------|
  | 9/20     | Themes Prevalient in There There | There There by Tommy Orange |

* Prompt
  One of...

  #+BEGIN_QUOTE
  In his Prologue, Orange claims that "we are the memories we don’t remember, which live in us, which we feel" (10). Choose one character from the novel, and explain how he/she embodies, revises, or refutes this claim. Be sure to explain/define the quotation and how it connects to the character you are discussing.
  #+END_QUOTE

  #+BEGIN_QUOTE
  Choose one character from the novel and discuss why his or her narrative is 1st, 2nd, or 3rd person. What effect does the form of narrativehave on how we read, understand, know the character?
  #+END_QUOTE

** Processing the prompt
   - Define "memories we don't remember" and "to feel"
   - Analyze a character and discuss how they embody/revise/refuse the above

* Quotes Bin

* Claim Synthesis

** Development
   - /Claim/
     - Why does the claim address the prompt?
     - How does the evidence support the claim?
       - 1
       - 2
       - 3
     - So what?

* Defluffication
  /Chosen Thesis Claim/

  - Point a
  - Point b
  - Point c

  So what? SO WHAT

  *Restated Claim*


  There's always the [[https://wp.ucla.edu/wp-content/uploads/2016/01/UWC_handouts_What-How-So-What-Thesis-revised-5-4-15-RZ.pdf][UCLA Writing Lab]].
