#+AUTHOR: Exr0n
#+TITLE: flo--managing complexity in the real world
* his intro / background
** used to be very into econ
** worked at world bank bc he thought it was a good place to meet people who were interested in math and econ and help the world
** was sent to a country (forgot) during communism->capitalism transition and saw that the forced capitalist policies were not working
** went into management because that allowed him to actually help
** sante fe institute
*** centeripece for a global movement to involve complexity in sciences accross disciplines
*** from los alamos national labs
*** 'universal relationships'
*** lots of nobel prizes
*** applications of graph theory and network theory, and lots of econ
**** understanding when societies are going to have a revolution, finiance, energy grid
* other related areas / interdisciplinary
** do individuals matter in history
** impacts on marketing based on faith studies?
* Overview
** this intersession is "interdisciplinary fixing of economics"
* Warmup
** insectivora, macroscelidea avg mass vs avg BMR, guess avg bmr for pholidota given avg mass
*** I just took the ratios and took a high and low
*** a few strategies for solving the problem
**** look for a common ratio (assume 0 mass = 0 BMR)
**** fit a line
**** it's actually not a linear relation, and the answer is relatively unexpected (much lower ratio)
** the monkey business illusion (ball passing -> miss other stuff)
*** when you get attached to a tool, you miss loads of other things
* universality
** examples
*** common limit theorem
**** lots of common processes produce gauseian distributions
***** thus, there is a "universality" in the normal distribution
*** other theorem? (something with gauss)
**** if things are often normal distributions, then statistics kind of works (because that's what it's all based on)
*** all mamals average the same number of heartbeats
**** small animals have fast hearts and die sooner, vice versa
*** metabolic rate (first warm up problem)
**** log log linear -> constant rate of savings? SUBLINEAR SCALING
**** constant increase in efficiency
**** roughly 3/4 or 2/3 exponent
**** exponent can be derived by networks (circulatory system)
***** where can this be applied?
****** many city statistics
******* 15% boost/saving for every size double for amount of gas stations, boost in gdp, # of patents, new AIDs cases, etc
* city
** superlinear scaling -> city should grow
** results
*** finite time singularity? when the growth curve goes vertical.. what does that mean. maybe environmental collapse
*** trying to increase GDP and decrease crime/AIDs by growing won't really work because both scale in the same way
* complexity
** core
*** taking a general tool and applying it elsewhere
** methodology
*** start with a data rich domain and find the generative mechinism, then apply to the data sparse
** definition of complexity
*** difficult to come up with a concrete definition
*** handwavey: systems of networked adaptive agents are complex
**** networked
***** networks have 'finite' sides (classifications of nodes)
***** complexity perspective: they provide an analyzable structure at the mezzo-level of granularity
****** ways networks are analyzed
******* degree of a node
******* betweenness centrality
******* eigenvector complexity?
******* avg path length
******* degree distribution
******* clustering
******* community structure
**** agents
***** assume that all companies or consumers are equal and if they differ, then they differ along one variable
***** agents are actually different though?
**** adpativity
***** such as evolutionarily inspired adaptation
****** genetic algorithms / evolutionary algorithms
****** often used to come up with a pretty good answer for a hard (NP complete or more difficult) problem
* random questions
** other structures?
*** many complex systems have network structures
*** celular automata
*** almost everything is a network, but they mean network like everyone knows everyone else
**** it's a nice assumption if you want to use calculus, but sometimes its a poor model
**** somewhere along the way, textbooks inverted it
**** try to find the underlying mechinism and build models that reflect it
** does economics stop new things from cropping up?
*** not cooridantedly, but if you edit a journal you will prefer to publish papers that exapand existing techniques instead of brand new ones
** evolutionary 'economics'
*** multiple equilibriums will be bounced between bc there is always variation that comes from new mutations
*** economics tries to pin systems to a 'perfect' equilibrium but with this complexity stuff you actually bounce between them
* classic economic curtain view
** pull a curtain on the state of the economy between equilibriums and just figure out where the next one is
** however, the actual policy that we care about is heavily affected by the transitions, thus we actually care
** case study: russian economic contraction
*** the 2008 recession was 5% and came back in 4 years. In russia, there was a 40% contraction and society really started to break down
*** jeffery somebody wanted mass privatization
**** government should value each company and make shares and give them out
**** doesn't account for dynamic something processes and didn't account for heterogenety
**** what happened? villagers sold their shares which kept getting resold
**** this is the problem with the curtain view: the transitions are the difficult parts that policy needs to hold up through
**** dengxiaopeng economic experiments were more effective than the mass shock transition
***** nomaclotora system? easier to get promoted if you run an experiment and it works
***** similar to how social credit experiments are being rolled out
***** it's like an evolutionary algorithm to search a complex landscape
* how does this change the way we think about policy
** for privitization, keep in mind how agents change and make decisions?
*** the only systems where game theory works is when everyone making the decision is a game theorist
** for science education, how do we influence the agents to make more risk adverse or better decisions?
*** teaching people about economics makes them behave more game theory rationally
* not perfect knowledge, so what?
** agents are different in many ways (not just one very controlled variable)
** agents don't have perfect information
** so, complex systems behave differently
*** cities are complex
*** firms are complex
*** industries
*** markets
*** individuals (brains)
** emergent properties
*** difficult to predict in a reductionist mindset
*** however, we organize knowledge from a reductionist mindset. This is already a mistake
*** phase transitions
**** nature of a system changes rapidly
**** it's difficult to undo the change
**** such as bear vs bull market in economics
* modern research
** collective intelligence
*** overview
**** used to have a very reductionist model (either group is one individual or boundedly rational; or everyone in it is universally networked and can make good collective decisions)
**** based on how individuals learn / communicate, you can get good or bad decisions
**** monkeys often organized themselves near critical points where it's easy to provoke internal war
***** makes sense if you believe in group level selection, bc if there is a famine, then everyone will spread around and maybe one group will survive
***** if this is a data rich domain, how can it be applied? Should we organize our teens so that they easily split and explore more areas?
** using complexity science to understand online hate speach
*** german data where people badge themselves as either 'reconquesta germania' or 'reconquestia internetta?'
*** conversations were analysed using NLP and researchers tried to understand what strategies worked to slow spread of hate or speed it up
** scaling and universiality in urban economic diversification
*** simon yule distribution? formed by a preferntial attachement mechinism?
**** if you use nix codes to do a frequency distribution
**** count the number of businesses in the most populous, second most populous, etc. then it forms the simon yule distribution, but the ordering was different.
***** thus, could there be some hidden mechinism that requires a specific relative distribution of diversity to grow?
* further reading resources
** google complexity economics
*** bryan arthur, dohan? framer, aeon? magazine
** complexityexplorer website
* when something goes wrong, did i pretend a complex system was simple?
** think about the moon trip
*** how much have we spent on the moon vs the war against poverty?
*** spent a lot of money but the problem wasn't solved
*** poverty or medical projects tend not to work because the underlying systems are complex
* education depertmant kerry kao?
