#+TITLE: Middle Passage
#+AUTHOR: Houjun Liu
#+COURSE: HIST301

* Discussion of the Middle Passage Reading
**Manifest destiny**: European-American team for subjugation

** Discussion of Viewpoints

*** Afrocentric View
- That there is a core, "pure" African view
- Middle passage did not change the African culture
- Cites cultural example in Haiti, etc. as the mark of cultural survival

*** Traditionalist View
- That there was no continuance from African culture after the middle passage
- Essentially, a new generation was born, and the culture did not survive the middle passage at all.

*** Cultural Syncretism
- Combination of the two?
- That the middle passage was a change and process of combination
- That African culture from different places was brought to the America to form a new element. A process of translation and a modification
- Creation of the "New World" multicultural system

** Defining Slavery
"Kidnapping." Weaponized processes of African communities, pitched cultures against each other. Europeans turned people against each other.

**"Divide & Conquer"**: British Colonial policy --- created conflicts and leveraged people against each other.

** Defining Culture
There is no Monolithic African culture. In fact, most of the African captives were shipped to the Caribbeans and South America.

** Is literature a good history?
Variety of perspectives in as derived for literature. The leverage of religion as the "Great Awakening".

The idea of "Black Churches" as a point of strength in the American south.

* Discussion of the Middle Passage Video

** Initialization
- Not initially /racial/ slavery; it was simply those who are enslaved are enslaved
- Due to labor shortage indentured servants were no longer viable
  - Due to shortage, had to turn to Africa
  - Also allowing

** Downfall
- Peak to downfall of slavery as an accepting institution
- Created coverage of the American revolution
- From Revolution Brits offer emaciation for Black Solders
- Large controversy: American demand of freedom to England is similar to that of Africans
  - Huge use of vocabulary --- "enslaved" by the policy
  - "all men were created equal", so what about..

- Constitutional Convention's 3/5 compromise
  - Justification of "All men equal"
  - Slavery though, still a sign of wealth 

** Discussion
Slavery also lead many into debt. British Bankers held debt, so revolution essentially allowed the institution of slavery to continue by absolving the debt of debters.
