#+OPTIONS: -:nil

---
author:  Exr0n
title:   20hist201 Unit 1 Essay Outline
source:  
context: 20hist201
---

[[file:./KBe20hist201Unit1Essay.md]]

e#+TITLE: 20hist201 Unit 1 Essay Outline
e#+AUTHOR: Exr0n
e#+CONTEXT: 20hist201

This is attempt 9

* Thesis Ideas
  “kennedy said that the ming and the ottomans suffered the same downfall, and while they did both ultamately struggle due to spanish silver inflation and european traders, the inflationary loop started with emperors in ming china while the ottomans just kinda got stomped + janissaries weren’t vere patriotic”

Although the economies of both the Ottoman and Ming empires suffered due to spiraling inflation and European trade, their misfortunes were not as similar as Kennedy suggests: the Ottomans' overstretched military was undermined by Europeans trading silver while the Mings' internal inflation spiral forced trade with and ultimately destruction by Europeans.

* Body 1 Choice A
  
** Topic
Kennedy said the ming and the ottomans suffered the same downfall due to centralization and economic troubles.

** Evidence
- "[the ottomans] were to falter [...] strikingly similar Ming decline" (Kennedy 11)
- "The system as a whole, like that of Ming China, increasingly suffered from some of the defects of being centralized, despotic, and severely orthodox in it's attitude toward initiative dissent, and commerce." (Kennedy 11)
- "dislike trade" similarities
  - "Merchants ant entrepreneurs (nearly all of whom were foreigners), who earlier had been encouraged, now found themselves subject to unpredictable taxes and outright seizures of property" (Kennedy 12) 
  - "The mandarins [had] a suspicion of trader" (Kennedy 8)
  - "[The mandarins] dislike of commerce and private capital [...]" (Kennedy 8)
    
* Body 1 Choice B
** Topic
Both the Ming and Ottoman empires suffered from economies weakened by instability and revolt caused by inflation.

** Evidence

*** Ming
**** DBQ doc 3
     Paraphrase: grain price dropped despite poor havests due to the deflation of silver. "As the price of grain falls, tillers of the soil recieve lower returns on their labors, and thus less land is put into cultivation."
     
**** Mann inflation ming
     "The entirely unsurprising result was a delirium of smuggling." (Mann 128)

* Body 2

** Topic
   Europeans used soft power to force the Ottoman empire into trading agreements that caused cripling inflation.

** Evidence

* Body 3

** Topic
   China's deflationary spiral 

** Evidence

* Conclusion
  

---
