#+OPTIONS: -:nil

---
author:  Exr0n
title:   20hist201 Unit 1 Essay Outline
source:  
context: 20hist201
---

[[file:./KBe20hist201Unit1Essay.md]]

e#+TITLE: 20hist201 Unit 1 Essay Outline
e#+AUTHOR: Exr0n
e#+CONTEXT: 20hist201

This is attempt 9

* Thesis Ideas
  “kennedy said that the ming and the ottomans suffered the same downfall, and while they did both ultamately struggle due to spanish silver inflation and european traders, the inflationary loop started with emperors in ming china while the ottomans just kinda got stomped + janissaries weren’t vere patriotic”

  Although the economies of both the Ottoman and Ming empires suffered due to spiraling inflation and European trade, their misfortunes were not as similar as Kennedy suggests: the Ottomans' overstretched military was undermined by Europeans trading silver while the Mings' internal inflation spiral forced trade with and ultimately destruction by Europeans.

* Body 1 Choice A
  
** Topic
   Kennedy said the ming and the ottomans suffered the same downfall due to centralization and economic troubles.

** Evidence
   - "[the ottomans] were to falter [...] strikingly similar Ming decline" (Kennedy 11)
   - "The system as a whole, like that of Ming China, increasingly suffered from some of the defects of being centralized, despotic, and severely orthodox in it's attitude toward initiative dissent, and commerce." (Kennedy 11)
*** "dislike trade" similarities
     - "Merchants ant entrepreneurs (nearly all of whom were foreigners), who earlier had been encouraged, now found themselves subject to unpredictable taxes and outright seizures of property" (Kennedy 12) 
     - "The mandarins [had] a suspicion of trader" (Kennedy 8)
     - "[The mandarins] dislike of commerce and private capital [...]" (Kennedy 8)

* Body 1 Choice B
** Topic
   Both the Ming and Ottoman empires suffered from viscious cycles of economic weakness and civil unrest.

** Evidence
*** Ming
**** Mann inflation ming: civil unrest
     - "The entirely unsurprising result was a delirium of smuggling (if business is outlawed, only outlaws will do business)." (Mann 128)
     - 1557 wokou struck back, "overwhelming all the resistence, the wokou 'abducted more than a thousdand people and burned more than a thousand homes.'" (Mann 133)
     
**** Mann ming trade: unstable economy
     - "'Coins recieved in the morning couldn't be used by evening,' explained a central-China gazetteer 1606." (Mann 137)
     - "the preferred money flipped arbitrarily from one Song emperor to another."
     - "To evaluate the [silvers'] purity, they used [silvermasters], who charged a fee for the evaluation and routinely cheated all parties." (Mann 138)

*** Ottomans
**** Military Economics
     - The Ottoman military was originally made of cavlary, who administered land and fought traditionally on horses, and Jannasaries, who fought on foot with modern technology and lived off wages. (Bulliet 490-1)
     - As the number and cost of the Janissary corps grew, "the turkish cavalry, which continued to disdain firearms, diminished". Then, the government tried to get rid of them by slowly reducing the number of landholding cavalrymen. (Bulliet 491)
     - The Ottoman government tried to save funds in the seventeenth century by abolishing the devshirme system, but the net increase in Janassaries and their "steady deterioration as a military force more than offset these savings". (Bulliet 491)

**** Civil unrest
     - "As the central government recovered control of the land, more and more cavalrymen joined the ranks of dispossesed troopers. Students and professors in the [religious colleges] similarly found it impossible to live on fixed stipends." (Bulliet 491)
     - "revolts that devastated Anatolia between 1590 and 1610 [caused by] former landholding cavalrymen, short-term soldiers released at the end of a campaign, peasants overburnedened by emergency taxes, and even impoverished students of religion" (Bulliet 491)

* Body 2
** Topic
   Europeans used soft power to force the Ottoman empire into trading agreements that caused cripling inflation and corruption.

** Evidence

*** Trade Agreements
    - "The penetration of European [trade] and the eventual domination of Ottoman commerce by Europeans [was] facilitated by a series of commercial treaties, known as the Capitulations." (Cleaveland 50)
    - The first treaty allowed French merchants to trade freely in Ottoman ports with minimal taxes, and allowed them to be punished under French instead of Ottoman-Islamic law. (Cleaveland 50)
    - The treaties were originally negotiated to facilitate trade with the militarily dominant Ottomans, but when the balance of hard power shifted in favor of Europe, the foreign merchants were able to "exploit the Capitulations to the disadvantage of the Ottomans". (Cleveland 50)
    - "By granting the various consuls juristiction over their nationals within the Ottoman Empire, the Capitulations accorded the consuls extraordinary powers that they abused with increasing frequency." (Cleveland 50)

*** Inflation -> government weakening
    - "[The] wave of inflation worked its way east, contributing to social disorder in the Ottoman Empire. European traders had more money available than Ottoman merchants and could outbid them for scarce commodities." The sudden devaluation of currency caused those living off fixed wages, especially the students and cavalry, to lose their livelihoods and revolt. (Bulliet 494)
    - "[Due to the inflation], some [cavalry landholders] saw their purchasing power decline so much that they could not report for military service." This played into the government hands because the government wanted to decrease it's reliance on the outdated cavalrymen.(Bulliet 491)
    - In the late sixteenth century Ottoman raw materials were increasingly traded for European products, which benefited merchants greatly but hurt the government. As inflation skyrocketed, the state could no longer pay it's military and "The Ottoman system [was] undermined." (Cleaveland 49)
    - "The shortage of revenue and the rise of inflation had a devastating effect on the large numbers of state employees on fixed salaries and created an atmosphere that fostered bribery and other forms of corruption." (Cleveland 50)
    - *The now unemployed cavalrymen helped fuel the civil unrest ultamately weakening the military and government from the inside.*

* Body 3

** Topic
   China opened up to European trade to reverse it's existing deflationary spiral, creating a European dependence on Chinese trade that ultamately incentivised it's destruction.

** Evidence
*** Silver deflation
    - Paraphrase: grain price dropped despite poor havests due to the deflation of silver. "As the price of grain falls, tillers of the soil recieve lower returns on their labors, and thus less land is put into cultivation." (DBQ doc 3)
    - 

* Conclusion
  China's new link with Europe ultamately resulted in Europe targeting and destroying China with hard power

  ---
