#+TITLE: Causes of WWI Essay Outline
#+AUTHOR: Exr0n
* prompt
  #+begin_quote
The political scientist Kenneth Waltz argues that the causes of war can be analyzed at three different levels: the individual human level, the state level, and the international system level. Those who view things from the first level believe that war is best explained by “selfishness,” “misdirected aggressive impulses,” or “stupidity” within the human psyche.

Those who favor the second level believe there are hostile or aggressive or revisionist states who, because of their form of government or other domestic issues, behave in a warlike manner while other states simply want to keep the peace (the status quo).

Those who favor the third level believe that the international system itself, because it is an anarchy with “no system of law enforceable” between states, and in which each state acts according to its own interest and reserves the right to use force to achieve its aims, makes war inevitable.

Analyze World War 1 according to one (or a blend) of these levels of analysis. Which best explains the general causes of the war as well as the specific sequence of events (including events that prolonged the war beyond the initial outbreak)?

Essays should cite from the Palmer reading, and, if you want to aim for the exemplary evidence standard, any of these [[https://drive.google.com/drive/folders/1KTggTDz3Yl7fT9MxwG4l25qMPNyiUioe?usp=sharing][primary sources as well]].


Other Submission guidelines: 3 pages, size 12 font, double-spaced. Citations should be in-line and formatted as (Authorname Pagenumber) i.e. (Kennedy 12). Include a Works Cited page in MLA format for the secondary sources. Primary sources do not need to be included in the Works Cited page, but their authorship and date and other relevant information should be introduced in your text when you cite them.

Tips: See the essay rubric guide below for questions to ask yourself as you write and revise.
[[https://docs.google.com/document/d/1cHuvVjKQbwUmRgRh2qbgk76dbMBoOcCgaBAasiznj6U/edit?usp=sharing][History essay rubric guide]]
  #+end_quote
* standards targets
** knowledge of history: reference specific events, places, dates, and people with a clear sense of chronology
** understanding patterns: define an array of historical trends { political, social, economic, cultural } and show how they affect each other
** argument and argumentation: address the prompt, explain events with a nuanced and precise sense of cause and effect. argument connects to broader trends and specific moments. needs a "so what" to demonstrate it's relevance
** use of evidence: use specific evidence from the 'widest array of sources' to support points in every paragraph
** written expression: use precise terminology and express nuanced thoughts, make clear intro, conclusion, and body paragraph structure clarified in thesis

* evidence

** primary sources

*** German historian Heinrich von Treitschke (1834-1896) glorified warfare quoted in Politics (1899-1900) (14 years before the war)

**** war is the only way out for 'an afflicted people'

**** forgo the ego and join the greater good (greatness of war)

**** those who appeal to peace / Christianity are cowards ('the leader should wield the sword')

**** (peace is reactionary -> bad) -> (banishing war -> banishing progress)

*** German general and influential military writer Friedrich von Bernhardi (1849-1930) in /Germany and the Next War/ (1911)

**** 'war is the father of all things', concept of war being necessary for all advancement of society

**** concept of 'the mighty must do what the mighty must' (international anarchy)

**** flourishing nations need more land and thus 'conquest becomes a law of necessity'

**** 'the right of conquest is universally acknowledged'... 'right to annexation'

**** 'might is at once the supreme right', basically war is necessary, correct, and natural

**** conclusion: exclusion of war 'must be demonstrably untenable'

*** French writer Ronald Dorgeles (1885-1973) recalls the mood in [Paris at the outbreak of the war

**** stunned -> 'What? War, was it? Well, then, let's go!'

**** people were ready and excited, 'but this time it was better than a song'

**** excited by cavalry and footsoldiers

** the book dude

*** level 1

**** ethnically diverse citizens (serbian nationalists, among others) want to not be part of austria hungary

*** level 2

**** germany rose up, making france and russia concerned (is this innevitable)

**** leaders expected war to come, so that may have made it more innevitable

***** TODO cite external research for this?                        :question:

*** level 3

**** game theoretic prisoner's dilemma style cost matrix

**** no common power to hold states accountable to the both-defend policy

**** security dilemma

* todos

** TODO read [[https://drive.google.com/drive/folders/1KTggTDz3Yl7fT9MxwG4l25qMPNyiUioe?usp=sharing][primary sources]].

** TODO review evidence/notes

** TODO come up with general frame

** TODO come up with argument, body paragraphs

** TODO { outline, write, edit } for standards
