#+TITLE: Victory for Democracy Essay
* meeting Arta 28 April 2021
** domestic politics, some on russia and some on germany
** russia kind of thought all the other countries were the same so it didn't matter who won
** imperialism, thus not democratic
*** british/french werent more democratic than tsars or germany or ottoman empire
*** imperialism is the highest stage of capitalism and thus not marxist
** imperialism vs democracy
*** gelvin: russia publicized the mandates, see gelvin
*** woodrow wilson also thought that imperialism was antidemocratic
*** believed that people should have equal say
*** didnt join league of nations bc senate didnt want to, but wilson may have wanted to
*** syria wanted to be an american mandate (in a comitte in 1919)
** body paragraphs
*** democracy won but not that democratic
*** mandates and middle east
**** turkey/germany became "democracies"
*** east asia: japan takes german colonies
** sentence structures
*** developing your own voice: recognize what you like in other people's writing
**** see their topic sentences and transitions
* marxism leninism
** +We are in favor of a democratic republic as the best form of state for the proletariat under capitalism. But we have no right to forget that wage slavery is the lot of the people even in the most democratic bourgeois republic.+
** democracy won but not that democratic
*** 'quoted the words of Lincoln: “When the white man governs himself, that is self-government; but when he governs himself and also governs others, it is no longer self-government; it is despotism.”' (Imperialism, the highest stage of capitalism, IX)
*** 'But we have no right to forget that wage slavery is the lot of the people even in the most democratic bourgeois republic.' (Lenin, state and revolution)
*** tragedy of the majority vs tragedy of the minority
** mandates and the middle east
*** list the countries
**** Syria
	 wanted united states or britain as mandate power, but were given to france
**** Lebanon
***** created by the french 'just enough territyory to make it economically viable and strategically useful, but not enough to threaten Christian dominence' Gelvin 191
**** Jordan
***** originally called "Trans-Jordan" or literally "across the jordan [river]"
***** solved a political problem but created an economic nightmare
***** external help provided 45% of government
**** Palenstine
***** got split in half and the east side was given to Abdallah as Jordan
***** the rest was "ruled like a crown colony [by the British] until they withdrew in 1948"
**** Iraq
***** also created to solve a political problem
***** joined ottoman provices of basra, baghdad, and mosul
***** given to Faysal, whose descendants ruled until 1958
***** looked like a good idea on paper (oil state), but 'system conspired against it's full political and economic development'
***** many (6?) ethnic groups
*** quotes
**** "however, Britain and France accepted the mandates so that they could retain control over those areas in which they felt they had vital interests" (gelvin 192)
**** 'the accumulation of vast agricultural estates by the new rural gentry, as well as the transformation of once independent pasturalists and farmers into tenant labor' (gelvin 194)
**** aristotle
***** 'So it is clear that a polis is of best size when it has a population large enough for a self-sufficient lifestyle but one that can be seen at a glance.' (From Dillon, Mathew, Lynda Garland. 2010. /Ancient Greece. Social and Historical Documents from Archaic Times to the Death of Alexander the Great./ New York: Routledge. Aristotle, /Politics/ 1326b11)
***** "aristocracy, either because the rulers are the best men, or because they promote the best interests of the state and citizens; when the many administer the state for the common interest, the government is called a constitutional government" "deviations from these are as follows: from kingship, tyranny (interests of the ruler); from aristocracy, oligarchy (interests of the wealthy); from constitutional government; democracy (interests of the poor)" Aristotle /Politics/ 1279a32, 1279b4
* outline
