#+TITLE: 29 March 2021 war freewrite
* why does war happen
** when people disagree and resort to force
* what would be required to put an end to war
** in most small groups, its possible to find a shared goal. however, on a national level we often don't plan that far ahead so we don't really work towards complex shared goals
** emergence towers (wait but why)
** just leaders
* is there such a thing as a just (or good, ethical, righteous) war; why/whynot
** for there to be a just war, there must be a common 'good'.
** however, is goodness relative? there seem to be some things which are generally considered good by most people, but its unclear that those are necessarily always good for everyone.
** if there is something that all parties agree are good, then that would be a just war?
** maybe there is a real ground-truth good, but we can't know what it is
** WWII: allied powers agreed that the holocaust was bad, but the nazis thought they were doing the right thing
** violence is not always bad. extend subjective experience
** war isn't just but one side may be in the moral correct
** all violence is unjust? there is always a more peaceful way
** abstract wars
