#+TITLE: The Innevitable Shift: How International Incentives Cause Individual Radicals

   At the turn of the twentieth century, Europe was locked in an arms race caused by international political and economic incentives. As tensions grew, cultural strifes inevitably intensified and ultimately sparked the war.
   Although a lack of enforcement of international order and ballooning militaries both incentivized and enabled WWI, the necessary spark was provided by individual civilian interests.

   Reinforcing international incentives such as the security dilemma and cult of the offensive put each of the international powers on edge, bringing the European powers closer to war.
   As a united Germany industrialized, both its population and industrial might grew to rival the French and British powers of the time. For instance, in 1880--nine years after Germany was officially unified--the German empire produced only 8.5% of the world's manufacturing output while Britain produce 22.9% of it. By 1913, deep into the security dilemma and one year before the war, Germany had surpassed British production and nearly doubled that of France's (Kennedy, Table 18).
   Contries tend to grow their military as they industrialize, if only for defensive purposes. As Germany doubled it's military population over three decades to challenge century-long British and French domination, nearby countries grew wary. As surpassed power and a failing empire, France and Russia grew wary of the newfound power between them. They allied with Britain in 1904 and 1907 respectively for fear of a coming war.
	As countries formed aliances and grew their militaries, opposing parties were forced to keep up in the arms race. This so called "security dilemma" doubled the number of military and navel personel worldwide in the 30 years between the German unification and the war, and nearly tripled the global warship tonnage (Kennedy, Table 19-20). A level two perspcetive would explain this aggression with Germany's expansionistic ideals, but even Britain's liberal parliamentary democracy quadrupled it's naval tonnage.
	Leaders at the time believed that preempting war would allow a fast and decisive victory. Even simplifying the outcomes to two countries and four possibilites, where each country either attacks or defends, greedy actors will choose to preempt war. As a result, each country prepared to invade it's neighboors, and European tensions grew.
	In fact, had a there been an international disencentive such as Mutually Assured Destruction, the relative ordering of possibilites and therefore the cost matrix would've prevented all out war between such parties. For example, in a nuclear scenerio where any attacked country can retaliate with their own warheads, the utility of each scenerio would be ordered as follows:

	| Utility | Our Actions | Their Actions |
	|---------+-------------+---------------|
	|       4 | Defend      | Defend        |
	|       3 | Attack      | Defend        |
	|       2 | Attack      | Attack        |
	|       1 | Defend      | Attack        |

	And in a two party system,

	| Top,Left | Attack | Defend |
	|----------+--------+--------|
	| Attack   | 2, 2   | 1, 3   |
	| Defend   | 3, 1   | 4, 4   |

	Although it may seem less risky for any given party to attack, the utility of both defend increases as weapons get stronger until both parties opt for a defense strategy under MAD. Modern mutually assured destruction has so far prevented all out war, and a lack of such disincentives made war more likely in the early 1900s.

** TODO BP2: upset / war-hungry people are required to spark the war

   As a side effect of this global militarization, the populous glorified and anticipated war. This level three influence on the level one psyche inflamed nationalist ideals across Europe and primed a now-ticking explosive.

	Popular works from the years leading up to the war describe how natural and necessary war is.
	For instance, German general and influential military writer Friedrich von Bernhardi (1849-1930) wrote in /Germany and the Next War/ (1911) that "War is a biological necessity of the first importance," and "The right of conquest is universally acknowledged." (CITE)
	As both a high-ranking general and a best-selling author, Bernhardi was in a unique position to influence the public opinion about war. His aggressive stance is not surprising given his military background, and his work was instrumental to priming Germany for battle. A nation cannot go to war without the support of the populous, as the citizens at large provide the troops, taxes, and labor to sustain warfare. Such vehement arguments swayed public opinion and opened the possibility of large-scale battle.

	A level two viewpoint may counter that Germany was naturally expansionist, but similar widespread sentiment in France suggests government structure and ideology were not a sufficient influence on public opinion. French writer Ronald Dorgeles (1885-1973) recalls the mood in Paris at the outbreak of war, writing "Suddenly a heroic wind lifted their heads. What? War, was it? Well then, let's go!" (CITE)
	The French parliamentary constitutional government had been weakened by civil unrest and would hardly have been able to force a uncooperative populous to war, but even the left-wing activists agreed in August of 1914 to refrain from calling strikes during the duration of the war in the Union Sacrée or Sacred Union. (CITE needed? :question: https://journals.sagepub.com/doi/abs/10.1177/026569147800800402?journalCode=ehqa) Thus, French actions could not have been primarily governmental influence, and such countries went to war due to level three influences on public opinion.

	An exclusively level one viewpoint may counter that German writers like Heinrich von Treitschke had been espousing and glorifying war decades before the rapid German industrialization beginning in 1970. However, the shift was more recent in other countries. For instance, Dorgeles notes the ideological one-eighty that socialist workers take upon hearing of war. "seeing their old dreams of peace crumble, [socialism workers] would stream out into the boulevards ... [but] they would cry 'To Berlin!,' not 'Down with war!'" (CITE) Although Germany's actions may be a result of it's level two structure, the level three influence on level one psyche is required to explain the actions of other states.

*** serbs in austria want to make yugoslavia (also bosnia?)

	As countries militarized and nationalist views grew, would ethnic and religious divisions intensify until something inevitably sparked war.
	In the case of WWI, the weakest link was the religious divide in Austria-Hungary. Over the course of a number of "Balkan crises," the Eastern Orthodox Serbs and Bosnians in southern Austria-Hungary grew discontent with the Roman Catholic Dual Monarchy that ruled the Habsburg empire--soon to be Austria-Hungary. As the Ottoman empire declined, the Serbs marked Bosnia as their own and were infuriated when Austria annexed Bosnia in 1908. When a the Balkan wars saw Austria cut Serbia off from the sea, Serbs both independent and Austrian grew exasperated and desperate. (Reader page 6 CITE)
	This chain of events was driven by recent level three influences: the ongoing security-dilemma-induced arms race had Germany's neighbors scrambling for land and power. States and citizens alike were expecting war, and looking to gain as much of an upper hand as possible before it broke out.

	level 3 -> level 1: individual actions cause stuff
	try to cite something external about expectations causing stuffs

	These level three influences also shifted the general psyche to become more war-like, pushing a few individuals near the top of the bell curve past a critical point.
	Cultural cracks plauge numerous states, but these

** TODO conclusion
   As power dynamics shifted around the turn of the twentieth century, the defined scarcity of state goals--such as the British ambition of having the largest navy--set off a chain of events that led ultimately and innevitably to global war. Without a change of level three incentives, such as a global mediator or mutually assured destruction, shifting power dynamics and the cult of the offensive will lead inescapably to security-dilemma-induced arms race and growing tensions which cause nationalist viewponts and breed rash individuals. Thus, international disincentives like mutually assured destruction are key to keeping political and economic incentives from inflaming ideological divides and causing warfare.
