#+TITLE: E Unit 2 Essay Planning + Outline
#+AUTHOR: Exr0n
* Prompt
  #+begin_quote
Option 1: "The concept of the balance of power was simply an extension of conventional wisdom. Its primary goal was to prevent domination by one state and to preserve the international order; it was not designed to prevent conflicts, but to limit them. To the hard-headed statesmen of the eighteenth century, the elimination of conflict (or of ambition or of greed) was utopian; the solution was to harness or counterpoise the inherent flaws of human nature to produce the best possible long-term outcome."

Henry Kissinger, Diplomacy

From one point of view, balance of power politics in the early modern period succeeded spectacularly, preventing a single European power from conquering the whole continent, although Napoleon almost succeeded. From another point of view, it exported great power conflict to the rest of the world, turning Africa, the Middle East, Asia, and the Americas into battlegrounds for rivalling European states. In the end, did the European balance of power succeed in its goal to, as Kissinger puts it, limit conflict and produce the “best possible outcome” from flawed human nature? Or did it magnify conflict and increase the likelihood of global war? Answer this question in a well organized essay using examples from multiple global regions.  (Kissinger, Mason, Roberts)
#+end_quote
* Outline
** Intro
*** Thesis
    Although Europe managed to remain disjoint and disunited, "balance of power politics" hardly limited conflict or produced a desireable <WC> outcome: Raison d'etat prolonged wars in Europe and exported conflict and oppression to India and the Caribbean.
** Richelieu + Raison d'etat
   Raison d'etat, the basis <WC> for 'balance of power politics' prolonged wars and levaraged suffering to greedily further each state, relying on similarly destructive intentions of surrounding states to balance power, but magnifying suffering along the way.
*** "In order to prolong the war and exhaust the belligrants, Richelieu subsidized the enemeies of his enemies, bribed, formented insurrections, [etc]" (Kissinger 62)
*** "France stood on the sidelines while Germany was devastated" (Kissinger 62)
*** "He seeks peace by means of war" (Quote on Kissinger 64, footnote 10)
*** "[Richelieu believed] the end justified the means" (Kissinger 64)
** India
   Not only did "conflict politics" <WC> prolong <WC> conflict <WC> in Europe, it also created an air of rivalary that brought other reigons, such as India, into the fray. <Expand and link to thesis?>
*** Seven years war in India
**** "India had been irresistably sucked into the worldwide conflict between British and French power" (Roberts 642)
**** "But the immediate cause of British rule in India was the worldwide struggle of England and France, which the English and French East India Companies joined in," (Trauttmann 177)
** Caribbean
   Like India, colonial rivalaries brought European exploitation and conflict to the Caribbean, wiping out the native population and driving the slave trade in the process.

*** Rivalary
**** "The spanish occupation of the larger Caribbean islands ... attracted the attention of the English, French and Dutch" (Roberts 650)
**** "[Tobacco colonies in the new world] rapidly became of great importance to England, not only because of the customs revenue they supplied, but also because [they] provided fresh opportunities for interloping in the trade of the Spanish empire." (Roberts 651)
**** "Production was for a long time held back by a shortage of labor, as the native populations of the islands succumbed to European ill-treatment and disease." (Roberts 650)
**** Lots of slaves: 6k slaves in 1643 but 50k in 1660 (Roberts 651)
**** "where colonial fronteers met and policing was poor and there were great prizes to be won, [the area] became the classical, indeed, legendary hunting ground of pirates." (Roberts 652)

** Conclusion
* Editing
** WC
*** TODO Need more synonyms for "balance of power politics"
**** power politics?
**** conflict politics?
