#+TITLE: Victory for Democracy Essay
* meeting Arta 28 April 2021
** domestic politics, some on russia and some on germany
** russia kind of thought all the other countries were the same so it didn't matter who won
** imperialism, thus not democratic
*** british/french werent more democratic than tsars or germany or ottoman empire
*** imperialism is the highest stage of capitalism and thus not marxist
** imperialism vs democracy
*** gelvin: russia publicized the mandates, see gelvin
*** woodrow wilson also thought that imperialism was antidemocratic
*** believed that people should have equal say
*** didnt join league of nations bc senate didnt want to, but wilson may have wanted to
*** syria wanted to be an american mandate (in a comitte in 1919)
** body paragraphs
*** democracy won but not that democratic
*** mandates and middle east
**** turkey/germany became "democracies"
*** east asia: japan takes german colonies
** sentence structures
*** developing your own voice: recognize what you like in other people's writing
**** see their topic sentences and transitions
* marxism leninism
** +We are in favor of a democratic republic as the best form of state for the proletariat under capitalism. But we have no right to forget that wage slavery is the lot of the people even in the most democratic bourgeois republic.+
** democracy won but not that democratic
*** 'quoted the words of Lincoln: “When the white man governs himself, that is self-government; but when he governs himself and also governs others, it is no longer self-government; it is despotism.”' (Imperialism, the highest stage of capitalism, IX)
*** 'But we have no right to forget that wage slavery is the lot of the people even in the most democratic bourgeois republic.' (Lenin, state and revolution)
*** tragedy of the majority vs tragedy of the minority
** mandates and the middle east
*** list the countries
**** Syria
	 wanted united states or britain as mandate power, but were given to france
**** Lebanon
***** created by the french 'just enough territyory to make it economically viable and strategically useful, but not enough to threaten Christian dominence' Gelvin 191
**** Jordan
***** originally called "Trans-Jordan" or literally "across the jordan [river]"
***** solved a political problem but created an economic nightmare
***** external help provided 45% of government
**** Palenstine
***** got split in half and the east side was given to Abdallah as Jordan
***** the rest was "ruled like a crown colony [by the British] until they withdrew in 1948"
**** Iraq
***** also created to solve a political problem
***** joined ottoman provices of basra, baghdad, and mosul
***** given to Faysal, whose descendants ruled until 1958
***** looked like a good idea on paper (oil state), but 'system conspired against it's full political and economic development'
***** many (6?) ethnic groups
*** quotes
**** "however, Britain and France accepted the mandates so that they could retain control over those areas in which they felt they had vital interests" (gelvin 192)
**** 'the accumulation of vast agricultural estates by the new rural gentry, as well as the transformation of once independent pasturalists and farmers into tenant labor' (gelvin 194)
**** lenin
***** 'And so in capitalist society we have a democracy that is curtailed, wretched, false, a democracy only for the rich, for the minority. The dictatorship of the proletariat, the period of transition to communism, will for the first time create democracy for the people, for the majority, along with the necessary suppression of the exploiters, of the minority. Communism alone is capable of providing really complete democracy, and the more complete it is, the sooner it will become unnecessary and wither away of its own accord. ' (Lenin, /State and Revolution/, 1917)
***** "[The state is] a special machine for the suppression of one class by another, and, what is more, of the majority by the minority. ... The systematic suppression of the exploited majority by the exploiting minority calls for the utmost ferocity and savagery ... slavery, serfdom and wage labor' (Lenin, /State and Revolution/, 1917)
**** aristotle
***** 'So it is clear that a polis is of best size when it has a population large enough for a self-sufficient lifestyle but one that can be seen at a glance.' (From Dillon, Mathew, Lynda Garland. 2010. /Ancient Greece. Social and Historical Documents from Archaic Times to the Death of Alexander the Great./ New York: Routledge. Aristotle, /Politics/ 1326b11)
***** "aristocracy, either because the rulers are the best men, or because they promote the best interests of the state and citizens; when the many administer the state for the common interest, the government is called a constitutional government" "deviations from these are as follows: from kingship, tyranny (interests of the ruler); from aristocracy, oligarchy (interests of the wealthy); from constitutional government; democracy (interests of the poor)" Aristotle /Politics/ 1279a32, 1279b4
* outline
** intro
*** As American historian Robert Roswell Palmer concludes in his chapter on the first world war, "the war was indeed a victory for democracy" (Palmer 696).
*** However, as Aristotle defines in /Politics/, the democracy is a deviation from a more pure form of government--the constitutional government or polity.
*** Furthermore, Engels and Lenin argue that the state is a machine for oppression of one class by another, in democratic republics no less than in monarchies.
** thesis
   Although the first world war was "indeed a victory for democracy," neither the victors nor the aftermath promoted widespread liberty.
** The victors of the first world war were democracies and tyrannies, not polities, and they did not promote widespread liberty.
*** <need something about wage slavery in the us, france, and britain>
** In addition, the new post-war Europen states was not conducive to liberty
   The new German republic, who professed their own ideals, did not feel responsible or attached to the previous regime. However, the treaty makers in Paris working in early 1919 under public pressure and "still in the heat of the war" dealt harshly to Germany---so much so that no German was willing to sign the Treaty of Versailles (Palmer 692-3).
   Although the German Empire was toppled and replaced with a more democratic government, the harsh treaty opened the way for Adolf Hitler's authoritarian regime. Hitler's election was technically democratic, but his regime stripped liberty from vast populations. Hitler used the democratic "rule of the poor" to rise to power, and quickly converted the state to a tyranny focused on his own political viewpoints. As Aristotle predicted, neither political agenda was beneficial to the citizen body as a whole. This surface-level "victory" for democracy did not lead to widespread liberty.
   An additional central goal of the Paris settlement was to allow national self-determination in Europe. The peacemakers attempted to create a sovereign nation for each people in eastern Europe. However, the intermixing of nationalities, lack of population exchange, and independence declarations of various states complicated the process. As a result, each new state found alien minorities within its borders and next of kin under foreign rule (Palmer 692).
   These cultural divides, suspiciously reminiscent of the Slavic misrepresentations in the pre-war Austrian Empire, led to numerous fractured states with disgruntled populations. The newly-formed buffer states, including Lithuania, Latvia, Poland, and Czechoslovakia,
** Furthermore, the colonial aftermath of the first world war was neither democratic nor liberating.
** Furthermore, no states could achieve widespread liberty?
** sources
*** Aristotle. /Politics/.
*** Lenin, 1917. /State and Revolution/.
*** Gelvin, James L. 2011. /The modern Middle East: a history/, New York: Oxford University Press.
*** Palmer et al. /A History of the Modern World/, 9th Edition.
*** Latvian Institute, 28 Feb. 2017. History of Latvia 1918-1940. www.latvia.eu/history-latvia-1918-1940.
