* Prompt
** Assignment guidelines

   After reading and analyzing Kincaid’s book, you have a better understanding of rhetorical purpose and techniques. Using Kincaid as inspiration, and using at least three of her techniques (parentheses, tone, anaphora, personal pronouns, labyrinthine sentence, em-dashes, etc.), write a rhetorical pastiche on one of the prompts below.

   In addition to your pastiche, please provide a short reflection. You should explain your rhetorical purpose as well as the techniques and elements of style you are trying to imitate (this means you will need to reflect a bit on Kincaid’s techniques, so that you can explain what aspects of her writing you’ve been inspired by). Your reflection is a chance to explain what you want to accomplish, in case it doesn’t fully come through in your piece, as well as to demonstrate your understanding of rhetorical techniques.

**  Prompts

*** Conflicts in identity and place
    In A Small Place Kincaid describes a conflicted relationship with identity, place, and the past, at times nostalgic, at times combative. Write about some aspect of your life—a part of your identity, a favorite place, your spoken/written languages, a relationship—that evokes contradiction and conflict for you. You may employ an implicit argument in your essay (like Kincaid’s), but you *must* have an explicit argument to articulate in your reflection.

*** Responsible travel
    Kincaid begins her text with a mockery of “you,” an assumed pasty-faced (read: white), European tourist visiting Antigua. Reflect on your position as a sometimes-tourist, privileged at least to some extent. Possible intended audiences include American friends and family unaware of the complicated power dynamics of travelling in non-Western and/or post-colonial countries, or the “locals” of said country: Antiguans, Peruvians, Costa Ricans, or others.


*** Solutions for issues based in poverty
    Critiques of philanthropy often suggest it is motivated by a colonial mindset (“white savior complex,” “white volunteerism”). Yet the fact remains that poverty proliferates and many aid organizations work to alleviate illness, destitution, and inequity. Use the Poverty Action Lab site (https://www.povertyactionlab.org/ (Links to an external site.)) to suggest a solution for some *manageable* issue based in poverty. Note about navigating the site: You may find it useful to start using either “Regions” or “Sectors”; “evaluations” and “publications” motivate issues and provide solutions (policy proposals).

** Evaluation and assessment
   - Understanding Literature: Form and Function
   - Close Reading and Argumentation
   - Structure and Mechanics
   - The Writer’s Voice
   - Responsibility


** Formatting and due dates

   Rhetorical essay: 600-800 words, double-spaced, include MLA-style header and title

   Reflection: at least 150 words, no more than 250 words, double-spaced



   Introduce Assignment: Week of 11/9

   Prewriting/notes/ideas due: 11/11

   Rough draft due for peer editing: 11/18

   Final due (including reflection): 11/20

* Outline
Uh, does that even apply? I want to use parenthises and I want to write about conflicting relationship

* Draft
