#+TITLE: Handout 20: Applications of FTC and Net Change Theorem
* cooling pizza
  Compute
  \[\begin{aligned}
  \int_{0}^{5} -110e^{-0.4t} dt
  \end{aligned}\]
  to the nearest degree.

  \[\begin{aligned}
  \int -110e^{-0.4t} dt = \frac{-110}{-0.4}e^{-0.4t} = 275e^{-0.4t}
  \end{aligned}\]

  Using the net change theorem,

  \[\begin{aligned}
  \Delta \beta \int_{0}^{5} -110e^{-0.4t} dt &= \int -110e^{-0.4(5)} dt &- \int -110e^{-0.4(0)} dt\\
  &= 275e^{-0.4(5)} &- 275e^{0}\\
  &= 37.21720289 &- 275\\
  &= 37.21720289 &- 275\\
  &= 300-237.78279711 &&\approx \boxed{62 \degree F}
  \end{aligned}\]
* definite integral as area under a curve
  The area in the triangle is 3 square units, so $5+3 = \boxed{8}$
* minimum value of $f(x) = \int_{-2}^{x^2-3x} e^{t^2} dt$

  \[\begin{aligned}
  \frac{d}{dx} f(x) =& e^{(x^2-3x)^2}(2x-3) = 0\\
  \implies& 2x-3 = 0 \\
  \implies& 2x=3\\
  \implies& \boxed{x=\frac{3}{2}}
  \end{aligned}\]
* approximate area under the curve graphically
  The function looks symmetric about $x=12$, so I will focus on $[0, 12]$.

  On the interval $[0, 6)$ a little under $6\cdot 100$ barrels of oil flow through.

  On the interval $[6, 12)$ a little over $6\cdot 100 + \frac{1}{2}6\cdot 100$ barrels flow through, for a total of $\approx 2(6*100+6*100+\frac{1}{2}6*100) = 3000$ barrels of oil.
* fundamental theorem of calculus but worded confusingly

  $F(x)$ is the antiderivative of $f(x)$, so differences in it are values of definite integrals.
