#+AUTHOR: Exr0n
#+TITLE: Axler 3.E ex18
* Problem
  #+begin_quote
	Suppose $T \in \mathcal L(V, W)$ and $U$ is a subspace of $V$. Let \pi denote the quotient map from $V$ onto $V/U$. Prove that there exists $S \in \mathcal L(V/U, W)$ such that $T = S \circ \pi$ if and only if $U \subseteq \text{null }T$.
  #+end_quote
  Intuitively, if we mod out part of the $\text{null }T$, then we should still be able to have a map that does what $T$ would do, and if we are able to do what $T$ would do, then we only removed part of $\text{null }T$ and lost no information.
* Reverse Direction by Contrapositive
  Intuitively, if we lost information, then we can't reconstruct what $T$ would do.

  Assume $U \nsubseteq \text{null }T$. There exists $v \in U$ s.t. $Tv \neq 0$. This is some of the "information" that was "lost". Because $v \in U$,
  \[ \pi v = U + v = U \]
  Because $U$ is the additive identity ($0$) in $V/U$, and because linear maps take zero to zero, $S \in \mathcal L(V/U, W)$ must take $\pi v = 0$ to zero.
  Thus, either $S(\pi v) \neq Tv$ or $S$ is not a linear map, both of which are contradictions.

  This shows that if $U \nsubseteq \text{null }T$, then $S \notin \mathcal L(V/U, W)$ or $T \neq S \circ \pi$. Thus, if $S \in \mathcal L(V/U, W)$ and $T = S \circ \pi$, then $U \subseteq \text{null }T$.

* Forward Direction
  Intuitively, if
