#+AUTHOR: Exr0n
#+TITLE: lin alg flo 20
* new schedule today :/
* Systems of equations, matrix equations, and vectors
* in class work! See [[./KBe20math530srcNull_space_and_column_space_intro.pdf]]
** parts of the question
*** How many solutions $x$ satisfy $Ax=0$?
*** When the answer is "infinitely many" what tools might we have to describe the size of that set?
*** How many possible outcomes $b$ are there for the equation $Ax=b$ for any $x$.
** $A=\begin{pmatrix}1&0\\0&1\end{pmatrix}$
*** How many solutions $x$ satisfy $Ax=0$?
    The only solution is x=0, because $Ax = x$.
*** When the answer is "infinitely many" what tools might we have to describe the size of that set?
    N/A
*** How many possible outcomes $b$ are there for the equation $Ax=b$ for any $x$.
    There can be infintely many vaules of $b$..?
** $A=\begin{pmatrix}1&0&0\\0&1&0\end{pmatrix}$
*** How many solutions $x$ satisfy $Ax=0$?
    Infinitely many (anything of the form $\begin{pmatrix}0\\0\\x\end{pmatrix}$)
*** When the answer is "infinitely many" what tools might we have to describe the size of that set?
    The columns of the matrix are linearly dependent
*** How many possible outcomes $b$ are there for the equation $Ax=b$ for any $x$.
