#+AUTHOR: Exr0n
#+TITLE: LInear Transformation Quiz
* Definitions
** Linear Map
   A linear map is a function/map from one vector space to another such that it satisfies the properties of additivity and homogeneity. Notationally, a linear map $T \in \mathcal L(V, W)$ satisfies $T(a) + T(b) = T(a+b) : a, b \in V$ and $\lambda Ta = T(\lambda a) : \lambda \in \mathbb F, a \in V$
** Null Space
   The null space of a linear map is the space of vectors that are sent to 0 by $T$, aka $\{v : v \in V \land Tv = 0\}$
** Column Space
   The column space of a linear map is the subspace of the codomain that is an output to the map, aka $\{w : Tv = w, v\in V, w\in W\}$
** Homogeneous system of equations
   A system of equations where all the right hand sides are $0$.
** Injective
   When each element in the column space of a map is mapped to by exactly one element in the domain, aka when $Tu = Tv \implies u = v$.
** Surjective
   When every element in the codomain is mapped to, aka the column space is the codomain, aka $W = \{Tv : v \in V\}$.
* Fundamental theorem of linear maps
  In a map $T \in \mathcal L(U, V)$ where $U$ is finite dimensional, $\text{dim }U = \text{dim range }T + \text{dim null }T$. Intuitively, the dimension of the input space is the dimension of everything that gets sent to zero plus everything that doesn't get sent to zero.
* Why is the range also called the "column space"?
  When a linear map is thought of as a matrix, (which Jana promises is always possible), everything that can be mapped to is a linear combination of the columns. Why columns instead of rows? The convention we use is to multiply operation matrices on the left, and the way matrix multiplication works means that when multiplying by an $n \times 1$ matrix each element ends up as the coefficient for a column in a linear combination. Thus, all possible $n \times 1$ matrices when taken as input to the operation matrix will create the span of the columns.
* Prove that for (presumably a linear map) $T \in \mathcal L(V, W)$ the null space is a subspace of $V$.
