#+AUTHOR: Exr0n
* Definitions
** affine subset
   An affine subset of a vector space $V$ is of the form $U + v$ where $U \subseteq V$ and $v \in V$.
** product space
   The product of some vector spaces $V_1 \times \cdots \times V_n$ is the set of lists of vectors with one from each respective space:
   \[ \{ (v_1, \ldots, v_n) : v_1 \in V_1, \ldots, v_n \in V_n \} \]
** quotient space
   A quotient space $V/U$ is the set of affine subsets $\{ U+v : v \in V \}$ (although some of those affine subsets are equivalent).
** equivalence relation
   An equivalence relation is a set of elements that are considered equivalent (equal to eachother). For example, in a vector space $U$, $U+0 = U+u \forall u \in U$.
* Why "product" and "quotient" are used to describe these operations
  The product of vector spaces is essentially a cartesian product. With real numbers, the product is like stacking copies of an operand in a new direction (product of two numbers for area of a plane, product of three for the volume of a space).
  Here, we are doing essentially the same thing for vector spaces (each vector is combined within a list with other vector spaces, but they do not interact with eachother and are orthagonal, in a sense).

  A quotient space is like taking (dividing) out part of a vector space. It's like taking a modulo because a subset ($U$) is collapsed to zero and some things become equivalent.
  It is like removing ("dividing") a subset of the basis (those that form a basis of $U$), where the basis itself can be represented as the cartesian product $\mathbb F^n$ (where $n$ is the dimension of $V$).
* Examples of quotient spaces
  Let $U = \{ (x, y) : y = 2x; x, y \in \mathbb R \}$. In $\mathbb R^2 / U$, vectors are of the form $U + v$ where $v \in V$ and any $v \in U$ is equivalent to $U+0$ or the line $y=2x$, which is the additive identity.
  Parallel spaces ("copies" that are shifted over) are the other elements in the space. The space is dimension one, since the copies can be shifted only in one orthoganal direction.
