#+TITLE: Upper Triangular Matrix
* upper triangular matrix                                               :def:
  A matrix in which all entries below the [[file:KBrefDiagonalOfAMatrix.org][diagonal]] are zero

  \[\begin{aligned}
  \begin{pmatrix}\lambda_1 & &*\\&\ddots&\\0&&\lambda _n\end{pmatrix}
  \end{aligned}\]
** results
*** Axler5.26 Conditions for upper-triangular matrix
	#+begin_quote
	Suppose $T ;i \mathcal{L} (V)$ and $v_1, \ldots, v_n$ is a basis of $V$. The following are equivalent:
	- the matrix of $T$ with respect to $v_1, \ldots, v_n$ is upper triangular
	- $Tv_j \in \ospan(v_1, \ldots, v_j)$ for each $j = 1, \ldots, n$
	- The span of each prefix of the basis is invariant under $T$.
	#+end_quote
*** Axler5.27 Over $\mathbb{C}$, every operator has an upper-triangular matrix
	#+begin_quote
	Suppose $V$ is a finite-dimensional complex vector space and $T \in  \mathcal{L} (V)$. Then $T$ has an upper-triangular matrix wrt some basis of $V$.
	#+end_quote
**** intuition
	 There are $n$ eigenvalues (fundamental theorem of linear algebra) and each one should have a corresponding eigenvector that can sweep out a column? What happens when an eigenvalue has higher multiplicity?
**** proof
***** induction on the dimension of $V$. use the fact that the first column can be found, then use the remaining basis vectors as a smaller subspace and do the same thing?
*** Axler5.30 Determination of invertibility from upper-triangular matrix
	#+begin_quote
	Suppose $T \in  \mathcal{L} (V)$ has an upper-tringular matrix wrt some basis of $V$. Then, $T$ is invertible iff all the entries on the diagonal of the upper-triangular matrix are nonzero.
	#+end_quote
